### ISSUE TITLE
死活对局trt版本用不了，open可以

### ISSUE THREAD

**Issue by awsjgy** [hzyhhzy/KataGo#21]
![Screenshot_2024-10-26-03-09-07-42_2665fb67b16260a8d818298cef8dc107](https://github.com/user-attachments/assets/ee4c352d-5411-483f-84c6-cca44a7666bc)
报错如下

**Comment by JinLi298** [comment]
同学，请问你解决问题了吗，可不可以加个联系方式交流一下
