### ISSUE TITLE
Some instructions would help

### ISSUE THREAD

**Issue by kogorman** [hzyhhzy/KataGo#22]
I'm very rusty in Java (though I taught it a decade or so ago)
I'm having trouble getting started installing this and integrating with HexGui.  A bit of a HOWTO would help.  Even if it's just a pointer to a directory and a command to make it all run.  Better yet would be the integration with HexGui.

**Comment by hzyhhzy** [comment]
Sorry but I know nothing about HexGui. It is better to ask him: https://github.com/selinger/hexgui

**Comment by hzyhhzy** [comment]
Or here https://github.com/selinger/katahex/issues

**Comment by hzyhhzy** [comment]
Or join the Hex discord server: https://discord.gg/4Nhsp6t3
